2024-05-01 11:19:56,566 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:06:09,759 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:06:19,809 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-01 12:06:25,457 [ERROR] django.request: Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\decorators\debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\generic\edit.py", line 141, in post
    if form.is_valid():
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\forms\forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\forms\forms.py", line 170, in errors
    self.full_clean()
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\forms\forms.py", line 373, in full_clean
    self._clean_form()
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\forms\forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\forms.py", line 202, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lvmch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
2024-05-01 12:09:54,934 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-01 12:09:55,044 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-01 12:10:00,066 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 12:10:02,443 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-01 12:10:02,537 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-01 15:31:57,734 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 15:32:07,794 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-01 15:32:53,234 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-01 15:33:03,290 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:39:45,985 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-02 08:39:56,012 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:40:17,064 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:40:17,268 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:40:52,889 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:41:03,806 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-02 08:41:13,837 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:41:15,142 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:41:15,339 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:51:10,521 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-02 08:51:20,555 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:51:30,605 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:51:40,647 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:51:50,313 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:51:50,507 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:56:43,629 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-02 08:56:53,662 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:57:03,699 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:57:13,732 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:57:18,832 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:57:19,034 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:58:13,469 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:59:12,120 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2024-05-02 08:59:22,163 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:59:31,167 [WARNING] django.request: Not Found: /favicon.ico
2024-05-02 08:59:32,215 [DEBUG] schedule: Running job Job(interval=10, unit=seconds, do=job, args=(), kwargs={})
2024-05-02 08:59:38,734 [DEBUG] asyncio: Using proactor: IocpProactor
2024-05-02 08:59:38,955 [DEBUG] asyncio: Using proactor: IocpProactor
